site_name: Ultimate Investigator
site_description: "A bot made to help automate investigations during Danganronpa roleplays."
site_url: https://ui.astrea.cc
theme:
  name: material
  custom_dir: overrides
  favicon: assets/ui_favicon.ico

  icon:
    logo: material/book-search
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
    - content.tooltips

extra_css:
  - assets/custom.css

repo_url: https://github.com/AstreaTSS/UltimateInvestigator
repo_name: AstreaTSS/UltimateInvestigator

nav:
  - Home: index.md
  - using_the_bot.md
  - server_setup.md
  - Legal:
    - Terms of Service: legal/tos.md
    - Privacy Policy: legal/privacy_policy.md
  - External Links:
    - Support Server: https://discord.gg/NSdetwGjpK
    - Ko-Fi Link: https://ko-fi.com/astreatss
    - Bot Source Code: https://github.com/AstreaTSS/UltimateInvestigator
    - Website Source Code: https://github.com/AstreaTSS/UIWebsite

copyright: >
  &copy Copyright 2021-2024 AstreaTSS
extra:
  social:
    - icon: fontawesome/solid/cookie
      link: "#__consent"
      name: Change Cookie Settings
    - icon: custom/topgg
      link: https://top.gg/bot/843994199187914753
      name: Top.gg Page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NSdetwGjpK
      name: Support Server
    - icon: simple/kofi
      link: https://ko-fi.com/astreatss
      name: Ko-Fi Page
    - icon: fontawesome/brands/github
      link: https://github.com/AstreaTSS/UIWebsite
      name: Website Source
    
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: umami
    url: !ENV UMAMI_SCRIPT_URL
    property: !ENV UMAMI_WEBSITE_ID

plugins:
  - search
  - offline
  - privacy
  - custom-cards:
      cards_layout_options:
        background_color: "#000000"
        logo: assets/ui_icon.jpg
  - autorefs
  - autolinks
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - md_in_html
  - abbr
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - mdx_breakless_lists
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
