site_name: Ultimate Investigator
site_description: "A bot made to help automate investigations during Danganronpa roleplays."
site_url: https://ui.astrea.cc
theme:
  name: material
  custom_dir: overrides
  favicon: assets/ui_favicon.ico

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: automatic
      primary: red
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link

extra_css:
  - assets/custom.css

repo_url: https://github.com/AstreaTSS/UltimateInvestigator
repo_name: AstreaTSS/UltimateInvestigator

nav:
  - Home: index.md
  - using_the_bot.md
  - server_setup.md
  - External Links:
    - Invite Bot: https://discord.com/oauth2/authorize?client_id=843994199187914753&permissions=8&scope=bot%20applications.commands
    - Support Server: https://discord.gg/NSdetwGjpK
    - Source Code: https://github.com/AstreaTSS/UltimateInvestigator

copyright: >
  &copy Copyright 2022-present AstreaTSS
extra:
  social:
    - icon: fontawesome/solid/cookie
      link: "#__consent"
      name: Change Cookie Settings
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NSdetwGjpK
      name: Support Server
    - icon: simple/kofi
      link: https://ko-fi.com/astreatss
      name: Ko-Fi Page
    - icon: fontawesome/brands/github
      link: https://github.com/AstreaTSS/UIWebsite
      name: Website Source
    
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: cloudflare
    property: !ENV CF_ANALYTICS_TOKEN

plugins:
  - search
  - offline
  - custom-cards:
      cards_layout_options:
        background_color: "#000000"
        logo: assets/ui_icon.jpg
  - autorefs
  - autolinks
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/custom.css

markdown_extensions:
  - admonition
  - md_in_html
  - abbr
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - mdx_breakless_lists
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons