name: "Pages Build"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Compress Images
      id: calibre
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: true

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install ./plugins

    - name: Build the documentation
      run: mkdocs build
      env:
        CF_ANALYTICS_TOKEN: ${{ vars.CF_ANALYTICS_TOKEN }}

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ui
        directory: site
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
